---
title: "Intro to Global Fishing Watch and Google Earth Engine"
description: "My slides from AERE2017"
date: "2017-07-06"
categories: [workshops, cloud, geospatial, fisheries, climate]
---

I'm busy getting settled into the [new job](http://economics.uoregon.edu/2017/04/05/meet-the-new-faculty-mark-colas-grant-mcdermott-woan-foong-wong/). (Probably should have posted something about that...) The Oregon summer is as splendid as everyone said it would be and I'm excited to explore my new surrounds.

Summer time is also conference time. Last month, I was invited to give a talk at the annual conference of the Association of Environmental and Resource Economists (AERE to her friends). More specifically, I presented at the [pre-conference workshop](http://www.aere.org/assets/docs/pre-conference%20workshop.pdf), which was all about the role that remote sensing and satellite data can play in environmental and natural resource economics. I've been very fortunate to gain a relatively early exposure to this world though my involvement with the [Global Fishing Watch](http://globalfishingwatch.org/) project, as well as [Google Earth Engine](https://earthengine.google.com/) -- the combined subjects of my talk. I'm strongly of the opinion that satellite data is underutilised by environmental economists at present, but will become a mainstay of the field in years to come.

The slides for my talk can be viewed [**here**](https://rawgit.com/grantmcdermott/aere2017/master/slides.html).

(Hit F11 to go fullscreen and "p" to see my speaker notes.)
